In [104]:
import torch
import torch.nn.functional as F

In [105]:
x = torch.rand((16,2))
labels = torch.ones((16))
out = F.softmax(x)
print(out.shape,labels.shape)

torch.Size([16, 2]) torch.Size([16])


/var/folders/zf/xbqvjkxn05x8yp70v_8s9r2w0000gn/T/ipykernel_25321/328881478.py:3: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  out = F.softmax(x)


In [106]:
out

tensor([[0.3709, 0.6291],
        [0.4975, 0.5025],
        [0.5212, 0.4788],
        [0.3667, 0.6333],
        [0.5906, 0.4094],
        [0.5109, 0.4891],
        [0.4159, 0.5841],
        [0.4967, 0.5033],
        [0.6253, 0.3747],
        [0.5537, 0.4463],
        [0.5791, 0.4209],
        [0.4585, 0.5415],
        [0.4435, 0.5565],
        [0.6009, 0.3991],
        [0.4648, 0.5352],
        [0.4202, 0.5798]])

In [107]:
out = out.argmax(dim=1)
out

tensor([1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1])

In [108]:
l= labels.reshape((-1))
l 

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [110]:
c = (l == out)
c.sum().item()

9